### ISSUE TITLE
关于爬虫运行的几个问题

### ISSUE THREAD

**Issue by weizhao9001** [TYZRPVX/hdfcrawler#7]
1. 四个task分别运行着哪些表？
2. 现在的任务分为日更和周更两种是吧？那是不是除了日更所在的task会一直运行，其他三个task运行结束后会自动提示finished？ 日更的会提示当日爬取finished吗？

**Comment by TYZRPVX** [comment]
请看[Panther](https://github.com/TYZRPVX/hdfcrawler/blob/master/src/edu/hit/ehealth/main/Panther.java)和[Mailer](https://github.com/TYZRPVX/hdfcrawler/blob/master/src/edu/hit/ehealth/main/util/mail/Mailer.java)在哪些地方引用
