### ISSUE TITLE
关于爬虫运行状态

### ISSUE THREAD

**Issue by weizhao9001** [TYZRPVX/hdfcrawler#8]
状态：好大夫爬虫已经运行两周，task1和2还在运行中，3和4已经结束。
主要有三个问题：
1. 报错，主要错误就是那个disk message 。。。
2.日更的表没有完成当日任务，能否单独分离出来优先运行？
3. task2为什么长时间没有结束，task2是不是任务有点多，所以一周爬不完？实验室这边可以提供机器。

**Comment by TYZRPVX** [comment]
disk message是指？
报错实际上无所谓，在代码中可以关掉所有错误信息。
正确做法是，通过数据库得到的结果反向推导那些数据缺失严重而非通过报错信息。

当然提供的服务器越多越好，便于分散内存、CPU压力

**Comment by weizhao9001** [comment]
嗯，报错我发群里了。
我最近再装一台电脑，可以把“日更"的task单独提取出来跑
另外task2还在运行，可以多分几个任务出来，这样压力小点
