### ISSUE TITLE
2016.4.26报错 task1

### ISSUE THREAD

**Issue by weizhao9001** [TYZRPVX/hdfcrawler#9]
![2](https://cloud.githubusercontent.com/assets/18001774/14812636/95cc5d5e-0bd0-11e6-8e34-fb68332dd0d7.png)
![1](https://cloud.githubusercontent.com/assets/18001774/14812589/53963162-0bd0-11e6-8489-765d211

**Comment by weizhao9001** [comment]
![1](https://cloud.githubusercontent.com/assets/18001774/14812696/d1bcabc0-0bd0-11e6-8e8f-12b70002b8f0.png)

**Comment by TYZRPVX** [comment]
可以设置JVM参数解决OOMError
